#!/usr/bin/env bash
# Bump the kimirelay CLI version everywhere, then rebuild the bundle.
#
# Split by what is reliable vs. what is fuzzy:
#  - Reliable (done here, deterministically): compute the next version and
#    write it into the two package.json files (the source of truth), then run
#    scripts/build-bundle.sh so site/latest.json + site/kimirelay.js ship
#    the new version.
#  - Fuzzy (delegated to a headless klaude run): finding every stale CLI
#    version reference scattered across docs/examples (llms.txt, TESTING.md,
#    READMEs, …) and telling it apart from dependency versions in pnpm-lock.yaml
#    or historical notes in design docs. An agent reads context; a regex cannot,
#    and a hardcoded file list goes stale the moment someone adds a new doc.
#
# Running it with the *current* version (e.g. `pnpm bump-version 0.5.25` when
# package.json is already 0.5.25) is a no-op on package.json but still sweeps
# the docs and rebuilds the bundle - useful to resync stale docs to the
# released version without cutting a new release.
#
# Usage:
#   pnpm bump-version              # bump patch (0.5.25 → 0.5.26)
#   pnpm bump-version patch         # same as above
#   pnpm bump-version minor         # 0.5.25 → 0.6.0
#   pnpm bump-version major         # 0.5.25 → 1.0.0
#   pnpm bump-version 0.6.2         # explicit version
#   pnpm bump-version --dry-run X   # preview; no writes, no agent, no bundle
#   pnpm bump-version --print-prompt X  # print the exact prompt sent to klaude

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DRY_RUN=0
PRINT_PROMPT=0
ARGS=()
for arg in "$@"; do
  case "$arg" in
    --dry-run|-n) DRY_RUN=1 ;;
    --print-prompt) PRINT_PROMPT=1 ;;
    *) ARGS+=("$arg") ;;
  esac
done
INPUT="${ARGS[0]:-patch}"
CURRENT="$(node -p "require('./package.json').version")"

# Resolve the target version: accept patch|minor|major keywords, or an
# explicit semver string (validated loosely).
case "$INPUT" in
  patch|minor|major)
    NEXT="$(node -e '
const parts = process.argv[1].split(".");
const maj = parseInt(parts[0], 10);
const min = parseInt(parts[1], 10);
const pat = parseInt(parts[2], 10);
const kind = process.argv[2];
if (kind === "major") console.log(`${maj + 1}.0.0`);
else if (kind === "minor") console.log(`${maj}.${min + 1}.0`);
else console.log(`${maj}.${min}.${pat + 1}`);
' "$CURRENT" "$INPUT")"
    ;;
  *)
    if [[ ! "$INPUT" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
      echo "error: '$INPUT' is not a valid version (use patch|minor|major or x.y.z)" >&2
      exit 1
    fi
    NEXT="$INPUT"
    ;;
esac

# Build the doc-sweep prompt once. Placeholders are substituted after so the
# heredoc body stays literal (backticks and version patterns are not expanded).
PROMPT=$(cat <<'EOF'
You are doing a version-bump sweep in the git repo at __ROOT__ (your current working directory). The kimirelay CLI release version is being set to __NEXT__ (previous canonical: __CURRENT__). The two package.json files are already at __NEXT__; your ONLY job is the documentation/examples sweep.

Find every reference to the kimirelay CLI release version across docs and example files, and change it to __NEXT__. These references are often stale (currently showing older values such as __CURRENT__ or earlier, e.g. 0.5.13 / 0.5.6). Update any string that denotes the kimirelay CLI version specifically, in whatever form it appears: bare (0.5.x), v-prefixed (v0.5.x), or quoted ("0.5.x").

Look in: site/public/llms.txt, TESTING.md, README files, and any *.md/*.mdx docs that cite "the installed CLI" version.

Hard rules - do NOT modify:
- package.json and packages/cli/package.json (already at __NEXT__)
- pnpm-lock.yaml - those version numbers are DEPENDENCY versions (e.g. httpxy@0.5.3, @vitejs/plugin-rsc >=0.5.20), NOT the CLI version
- site/latest.json and site/kimirelay.js - regenerated by the build step that runs after you
- anything under node_modules/, dist/, .vercel/, .git/, or site/public/kimirelay.js
- historical/past version mentions in design or planning docs (e.g. PLAN.md has "version": "0.4.2" as an old example) - only update references to the CURRENT CLI release version, not historical context
- dependency or registry version strings of any kind

Do NOT run the bundle build, do NOT commit, do NOT run tests. Just edit the doc files. Keep every change to the version string only - do not reword surrounding prose.

When done, output a concise report: each file you changed, and for each the old value → __NEXT__. If you found nothing to change, say so explicitly.
EOF
)
PROMPT="${PROMPT//__ROOT__/$ROOT}"
PROMPT="${PROMPT//__CURRENT__/$CURRENT}"
PROMPT="${PROMPT//__NEXT__/$NEXT}"

if [[ "$DRY_RUN" == 1 ]]; then
  echo "[dry-run] current: v${CURRENT}  →  target: v${NEXT}"
  echo "[dry-run] would rewrite: package.json, packages/cli/package.json"
  echo "[dry-run] would run headless klaude to sweep doc version refs → v${NEXT}"
  echo "          (e.g. site/public/llms.txt, TESTING.md, other *.md docs)"
  echo "[dry-run] would run: bash scripts/build-bundle.sh"
  exit 0
fi

if [[ "$PRINT_PROMPT" == 1 ]]; then
  printf '%s\n' "$PROMPT"
  exit 0
fi

echo "Releasing kimirelay v${CURRENT} → v${NEXT}"

# 1. Update both package.json files in place, preserving 2-space indent +
#    trailing newline. JSON.parse keeps key order, so only the version changes.
update_pkg() {
  local file="$1"
  node -e '
const fs = require("node:fs");
const [path, next] = [process.argv[1], process.argv[2]];
const pkg = JSON.parse(fs.readFileSync(path, "utf8"));
pkg.version = next;
fs.writeFileSync(path, JSON.stringify(pkg, null, 2) + "\n");
' "$file" "$NEXT"
}
update_pkg "$ROOT/package.json"
update_pkg "$ROOT/packages/cli/package.json"
echo "✓ package.json + packages/cli/package.json → $NEXT"

# 2. Sweep stale CLI-version references in docs/examples via headless klaude.
#    The agent reads context, so it can skip dependency versions in pnpm-lock
#    and historical mentions in design docs - something a regex cannot do.
if command -v klaude >/dev/null 2>&1; then
  TCLAUDE=(klaude)
elif command -v kimirelay >/dev/null 2>&1; then
  TCLAUDE=(kimirelay claude)
else
  echo "error: klaude/kimirelay not on PATH - install the CLI first" >&2
  exit 1
fi

echo "→ sweeping doc version refs to v${NEXT} via headless klaude…"
"${TCLAUDE[@]}" -p "$PROMPT" --dangerously-skip-permissions --output-format text < /dev/null 2>&1

# 3. Rebuild the bundle so site/kimirelay.js and site/latest.json ship the
#    new version. build-bundle.sh reads the root package.json we just bumped.
echo "→ rebuilding bundle…"
bash "$ROOT/scripts/build-bundle.sh"

echo "✓ released v${NEXT} - review with \`git diff\`, then commit."